### ISSUE TITLE
Tracking comments about Unbox and friends

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly#2489]
- [ ] Expose deriveUnbox and deriveUnboxWith via the Internal.Data.Unbox module
  as well.
- [ ] Combine Unbox and Serialize exposed modules.
- [ ] Have more elaborate round tripping tests for TH deriving.

- We don't export it via Array modules. Unbox is not specific to Arrays.

**Comment by adithyaov** [comment]
This is done, I believe.
