### ISSUE TITLE
0.8.0 Miscellaneous tasks

### ISSUE THREAD

**Issue by pranaysashank** [composewell/streamly#699]
Issues that don't merit their own issues or pull requests that need to be finished before 0.8.0. 
Edit this issue as needed.

- [x] foldlM', concatMapWith needs a `/Since: 0.8.0 (signature change)/` annotation. (#740)
- [x] Update instructions in `benchmark/README.md` to use `cabal bench` name spaced components - Not relevant as we only mention running them using ./bench.sh and it does the right thing. (#753) 
- [x] Add instructions to update streamly-examples on release in the Maintainers guide. (#744)
- [x] Add instructions to do a coverage build before release in the Maintainers guide. - Already present in the guide.
- [x] Mention migration of streamly-examples in Changelog.md
